import type { IconType } from "react-icons";
import {
  SiTypescript,
  SiJavascript,
  SiReact,
  SiVite,
  SiNextdotjs,
  SiNodedotjs,
  SiPython,
  SiRust,
  SiGo,
  SiTailwindcss,
  SiDocker,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiGraphql,
  SiExpress,
  SiNestjs,
  SiVuedotjs,
  SiAngular,
  SiSvelte,
  SiWebpack,
  SiEsbuild,
  SiJest,
  SiVitest,
  SiCypress,
  SiStorybook,
  SiGit,
  SiGithub,
  SiGitlab,
  SiVercel,
  SiNetlify,
  SiGooglecloud,
  SiFigma,
  SiSupabase,
  SiFirebase,
  SiPrisma,
} from "react-icons/si";

export const techStackIcons: Record<string, IconType> = {
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  React: SiReact,
  Vite: SiVite,
  NextJS: SiNextdotjs,
  NodeJS: SiNodedotjs,
  Python: SiPython,
  Rust: SiRust,
  Go: SiGo,
  TailwindCSS: SiTailwindcss,
  Tailwind: SiTailwindcss,
  tailwindcss: SiTailwindcss,
  Docker: SiDocker,
  PostgreSQL: SiPostgresql,
  MongoDB: SiMongodb,
  Redis: SiRedis,
  GraphQL: SiGraphql,
  Express: SiExpress,
  NestJS: SiNestjs,
  Vue: SiVuedotjs,
  Angular: SiAngular,
  Svelte: SiSvelte,
  Webpack: SiWebpack,
  Esbuild: SiEsbuild,
  Jest: SiJest,
  Vitest: SiVitest,
  Cypress: SiCypress,
  Storybook: SiStorybook,
  Git: SiGit,
  GitHub: SiGithub,
  GitLab: SiGitlab,
  Vercel: SiVercel,
  Netlify: SiNetlify,
  GCP: SiGooglecloud,
  Figma: SiFigma,
  Supabase: SiSupabase,
  Firebase: SiFirebase,
  Prisma: SiPrisma,
};

export const validTechStacks = Object.keys(techStackIcons) as [
  string,
  ...string[],
];
