name: CI

on: [push, workflow_dispatch]

jobs:
  test-framework:
    name: Run tests
    runs-on: ${{ matrix.runner }}
    if: github.actor == github.repository_owner || github.event_name == 'push'
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            platform: linux-x64
            node-version: 22.x
          - runner: ubuntu-latest
            platform: linux-x64
            node-version: 20.x
          - runner: ubuntu-latest
            platform: linux-arm
            node-version: 22.x
          - runner: ubuntu-latest
            platform: linux-arm
            node-version: 20.x
          - runner: windows-latest
            platform: windows-x64
            node-version: 22.x
          - runner: windows-latest
            platform: windows-x64
            node-version: 20.x
          - runner: macos-latest
            platform: macos-arm
            node-version: 22.x
          - runner: macos-latest
            platform: macos-arm
            node-version: 20.x

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 10.11.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-${{ matrix.platform }}-${{ matrix.node-version }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.platform }}-${{ matrix.node-version }}-turbo-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --reporter=silent

      - name: Run tests
        run: pnpm exec turbo run test --filter='rpress'
        env:
          CI: true
          DO_NOT_TRACK: 1

      - name: Run Build
        run: pnpm build
        env:
          CI: true
          DO_NOT_TRACK: 1
  test-website:
    name: Test Website
    runs-on: ubuntu-latest
    needs: test-framework
    if: github.actor == github.repository_owner || github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Test in Docker with Playwright
        uses: docker://mcr.microsoft.com/playwright:v1.55.0-noble
        with:
          args: bash -c "npm install -g pnpm@10.11.0 && pnpm install --frozen-lockfile && pnpm test"
        env:
          CI: true
          DO_NOT_TRACK: 1
