name: CI

on:
  # pull_request: 
  #   types:
  #     [opened, reopened, edited]
  # Allow manual runs by repo owners via workflow_dispatch
  workflow_dispatch:


jobs:
  test:
    name: Run tests 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 10.11.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --reporter=silent

      - name: Run Build
        run: DO_NOT_TRACK=1 pnpm build
        env:
          CI: true

      - name: Run tests
        run: DO_NOT_TRACK=1 pnpm test
        env:
          CI: true
          DO_NOT_TRACK: 1
